<script type="text/javascript" src="/Sfive/public/js/home.js"></script>
<div id="news" class="box ui-corner-all">
    <div class="ui-widget-header ui-corner-top">
        Tin tức & Sự kiện
    </div>
    <div id="events">
        <script>
            $("#events").load("/Sfive/public/home/index/events");
        </script>
    </div>
    <br>
</div>
<div style="margin-top: 10px" class="box ui-corner-all">
    <div class="ui-widget-header ui-corner-top">
        Khuyến mãi & học bổng
    </div>
    <div id="scholarship">
        <script>
            $("#scholarship").load("/Sfive/public/home/index/scholarship");
        </script>
    </div>

    <br>
</div>
<div style="margin-top: 10px" class="box ui-corner-all">
    <div class="ui-widget-header ui-corner-top">
        Sfive với cộng đồng
    </div>
    <div id="society">
        <script>
            $("#society").load("/Sfive/public/home/index/society");
        </script>
    </div>

    <br>
</div>

<div style="margin-top: 10px" class="box ui-corner-all">
    <div class="ui-widget-header ui-corner-top">
        Kinh nghiệm học tiếng anh
    </div>
    <div id="learnExp">
        <script>
            $("#learnExp").load("/Sfive/public/home/index/learnexp");
        </script>
    </div>
    <br>
</div>