<script>
    $(document).ready(function() {
        $("#left-menu").hide();
        $("#entry").width('76.7%');
        layoutAction.run_marquee();
    });
</script>
<div class="ui-widget-header ui-corner-top">
    <?php echo $this->title ?>
</div>
<br>
<div>
    <div style="margin: 25px; margin-top: 0px">
        <?php
        echo $this->content
        ?>
    </div>
</div>
<br>
<div class="fb-comments" data-href="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>" data-width="750"></div>