<script type="text/javascript" src="/Sfive/public/js/post.js"></script>
<link href="/Sfive/public/css/post.css" media="screen" rel="stylesheet" type="text/css">


<div id="MyTableContainer">
    <div class="filtering" >
        <form>
            <?php
            echo $this->formRow($this->form->get('title'));
            echo $this->formRow($this->form->get('menu'));
            ?>
            <button type="submit" id="LoadRecordsButton">Load records</button>
        </form>
    </div>
</div>