<table style="width: 180px">
    
    
    <tr>
        <td>
            <?php echo $this->title ?>
        </td>
        <td id="thuhoai0810">
            <div id="SkypeButton_Chat_thuhoai0810_1">
                <script type="text/javascript">
                    Skype.ui({
                        "name": "chat",
                        "element": "SkypeButton_Chat_thuhoai0810_1",
                        "participants": ["thuhoai0810"],
                        "imageSize": 11
                    });
                </script>
            </div>
        </td>
        <td>
            <a href="ymsgr:sendIM?tuvannewocean06">
                <img style="padding-bottom: 7px;" src="http://opi.yahoo.com/online?u=tuvannewocean06&m=g&t=0" border="0" alt="" />
            </a>
        </td>
    </tr>
</table>