<?php
$this->headTitle("Quản lý tài liệu");
?>
<h2><?php echo $this->title ?></h2>
<p>
    <a href="<?php echo $this->url('documents', array('action' => 'webupload')); ?>">Upload tài liệu</a>
</p>
<table class="table">
    <tr>
        <th>Tên tài liệu</th>
        <th>Định dạng</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    $alldocs = $this->docs;
    foreach ($alldocs as $doc) :
        ?>
        <tr>
            <td><?php echo $this->escapeHtml($doc->getFileName()); ?></td>
            <td><?php echo $this->escapeHtml($doc->getFileType()); ?></td>
            <td>
                <a href="<?php echo $doc->getLink() ?>">View</a>
                <a href="<?php echo $this->url('documents', array('action' => 'edit', 'id' => $doc->getId())); ?>">Edit</a>
                <a href="<?php echo $this->url('documents', array('action' => 'delete', 'id' => $doc->getId())); ?>">Delete</a>

            </td>
        </tr>
    <?php endforeach; ?>
</table>
