<!-- Scripts -->
<?php $this->headScript()->prependFile($this->basePath() . '/js/upload.js'); ?>

<div align="center">
    <h3>
    <?php
    echo $this->action; // put your code here
    ?>
</h3>
    <embed id="upload" wmode="transparent" 
           allowscriptaccess="always" 
           allowfullscreen="true" style=""
           width="100%" height="400px" 
           src="http://localhost/webupload-debug/webupload.html?debug=true" 
           >
</div>
