<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Trung tâm tiếng Anh Sfive'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/faviconsf.ico'))
                ->prependStylesheet($this->basePath() . '/plugins/jquery-toastmessage-plugin/resources/css/jquery.toastmessage.css')
                ->prependStylesheet($this->basePath() . '/plugins/jQuery-Validation/css/validationEngine.jquery.css')
                ->prependStylesheet($this->basePath() . '/plugins/jtable/lib/themes/lightcolor/orange/jtable.css')
                ->prependStylesheet($this->basePath() . '/plugins/apycom.com-15-orange/menu.css')
                ->prependStylesheet($this->basePath() . '/css/layout.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/plugins/jquery-ui-1.10.3/css/sfive-theme/jquery-ui-1.10.3.custom.css')
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/plugins/blockUI/jquery.blockUI.js')
                ->prependFile($this->basePath() . '/plugins/jquery-toastmessage-plugin/javascript/jquery.toastmessage.js')
                ->prependFile($this->basePath() . '/plugins/jQuery-Validation/js/languages/jquery.validationEngine-vi.js')
                ->prependFile($this->basePath() . '/plugins/jQuery-Validation/js/jquery.validationEngine.js')
                ->prependFile($this->basePath() . '/plugins/ckeditor/ckeditor.js')
                ->prependFile($this->basePath() . '/plugins/jtable/lib/jquery.jtable.js')
                ->prependFile($this->basePath() . '/plugins/jquery-slideshow/jquery.slides.js')
                ->prependFile($this->basePath() . '/plugins/apycom.com-15-orange/menu.js')
                ->prependFile($this->basePath() . '/js/layout.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/plugins/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.js')
                ->prependFile($this->basePath() . '/js/jquery-1.10.2.js')
        ?>
        <script type="text/javascript" src="http://cdn.dev.skype.com/uri/skype-uri.js"></script>
    </head>
    <body style="background-color: rgb(32, 13, 0)">
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        <div id="pages">
            <div id="logo" class="ui-corner-all" >
                <img src="<?php echo $this->basePath() . '/img/sfivelogo.gif' ?>" style="height: 85px; margin: 10px"/>
            </div>
            <div id="menu">
                <ul class="menu">
                    <li><a href="<?php echo $this->url('home') ?>"><span>Trang chủ</span></a></li>
                    <li><a href="#"><span>Khám phá Sfive</span></a>
                        <div><ul>
                                <li><a href="<?php echo $this->url('discoversfive') . "about" ?>"><span>Chúng tôi là ai?</span></a></li>
                                <li><a href="<?php echo $this->url('discoversfive') . "whychoosesfive" ?>"><span>Tại sao chọn Sfive?</span></a></li>
                            </ul></div>
                    </li>
                    <li><a href="<?php echo $this->url('discoversfive') . "teachers" ?>"><span>Đội ngũ giáo viên</span></a>
                    </li>
                    <li><a href="<?php echo $this->url('application') ?>" ><span>Góc học viên</span></a>
                        <div>
                            <ul>
                                <li><a href="<?php echo $this->url('application') ?>"><span>Cảm nghĩ học viên</span></a></li>
                                <li><a href="<?php echo $this->url('application') ?>"><span>Thành tích xuất sắc</span></a></li>
                                <li><a href="<?php echo $this->url('application') ?>"><span>Góc thư giãn</span></a></li>
                                <li><a href="<?php echo $this->url('application') ?>"><span>Gallery</span></a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="<?php echo $this->url('application') ?>"><span>Góc tài liệu</span></a>

                    </li>
                    <li class="last"><a href="<?php echo $this->url('application') ?>"><span>Liên hệ & Tuyển dụng</span></a></li>
                </ul>
            </div>
            <div id="banner" class="ui-widget-content ui-corner-all">
                <div id="slides" style="height: 100%; width: 100%">
                    <img src="<?php echo $this->basePath() . '/img/example-slide-1.jpg' ?>"/>
                    <img src="<?php echo $this->basePath() . '/img/example-slide-2.jpg' ?>"/>
                    <img src="<?php echo $this->basePath() . '/img/example-slide-3.jpg' ?>"/>
                    <img src="<?php echo $this->basePath() . '/img/example-slide-4.jpg' ?>"/>
                </div>
            </div>
            <div id="runtext" style="left: 0px;" class="marquee" >
                <span style="color: #D4FC03">
                    Việc xếp hàng chờ mua iPhone mới giống như là một truyền thống mỗi khi Apple giới thiệu sản phẩm mới. Tuy nhiên lần này thì nó diễn ra khá sớm và ngay cả khi Apple còn chưa nói ra chiếc iPhone mới sẽ như thế nào.... 
                </span>
            </div>
            <div id="content" >
                <div id="left-menu" class="ui-widget-content ui-corner-all">
                    <div class="panel-header ui-widget-header">
                        Các khóa học
                    </div>
                    <div id="accordion">
                        <h3>Tiếng Anh giao tiếp</h3>
                        <ul class="jquery-menu" id="news">
                            <li><a href="<?php echo $this->url('cackhoahoc') . 'tienganhgiaotiep/starter' ?>">Starter</a></li>
                            <li><a href="<?php echo $this->url('cackhoahoc') . 'tienganhgiaotiep/elementary' ?>">Elementary</a></li>
                            <li><a href="<?php echo $this->url('cackhoahoc') . 'tienganhgiaotiep/preintermediate' ?>">Pre-Intermediate</a></li>
                            <li><a href="<?php echo $this->url('cackhoahoc') . 'tienganhgiaotiep/intermediate' ?>">Intermediate</a></li>
                            <li><a href="<?php echo $this->url('cackhoahoc') . 'tienganhgiaotiep/advanced' ?>">Advanced</a></li>
                        </ul>
                        <h3>Tiếng Anh thương mại</h3>
                        <ul class="jquery-menu" id="news">
                            <li><a href="<?php echo $this->url('application') ?>">Starter</a></li>
                            <li><a href="<?php echo $this->url('application') ?>">Elementary</a></li>
                            <li><a href="<?php echo $this->url('application') ?>">Pre-Intermediate</a></li>
                            <li><a href="<?php echo $this->url('application') ?>">Intermediate</a></li>
                            <li><a href="<?php echo $this->url('application') ?>">Advanced</a></li>
                        </ul>
                        <h3>Ngữ pháp tiếng Anh</h3>
                        <ul class="jquery-menu" id="news">
                            <li><a href="<?php echo $this->url('application') ?>">Ngữ pháp cơ bản</a></li>
                            <li><a href="<?php echo $this->url('application') ?>">Ngữ pháp nâng cao</a></li>
                        </ul>
                        <h3>Luyện thi TOEIC</h3>
                        <ul class="jquery-menu" id="news">
                            <li><a href="<?php echo $this->url('application') ?>"> Dưới 450</a></li>
                            <li><a href="<?php echo $this->url('application') ?>">Từ 450 đến 650</a></li>
                            <li><a href="<?php echo $this->url('application') ?>"> Trên 650</a></li>
                        </ul>
                        <h3>Luyện thi IELTS</h3>
                        <ul class="jquery-menu" id="news">
                            <li><a href="<?php echo $this->url('application') ?>"> Dưới 4.0</a></li>
                            <li><a href="<?php echo $this->url('application') ?>"> Từ 4.0 đến 5.0</a></li>
                            <li><a href="<?php echo $this->url('application') ?>"> Từ 5.0 đến 6.5</a></li>
                            <li><a href="<?php echo $this->url('application') ?>"> Trên 6.5 </a></li>
                        </ul>
                        <h3>Tiếng Anh theo yêu cầu</h3>
                    </div>
                </div>
                <div id="entry" class="ui-widget-content ui-corner-all">
                    <?php echo $this->content; ?>
                </div>
                <div id="right-menu" >
                    <div id="shedule" style="width: 100%;" class="ui-widget-content ui-corner-all">
                        <div class="panel-header ui-widget-header ui-corner-top">
                            Hoạt động
                        </div>
                        <div id="menu-schedule">
                            <ul class="jquery-menu">
                                <li><a href="<?php echo $this->url('events') . "lich_khai_giang" ?>"><span>Lịch khai giảng</span></a></li>
                                <li><a href="<?php echo $this->url('register') ?>"><span>Đăng ký nhận khuyến mãi</span></a></li>
                                <li><a href="<?php echo $this->url('application') ?>" ><span>CLB tiếng Anh Sfive</span></a>
                                </li>
                                <li><a href="<?php echo $this->url('application') ?>" ><span>Lớp học tăng cường</span></a>
                                </li>
                                <li><a href="<?php echo $this->url('application') ?>" ><span>Kết quả các lớp học</span></a>
                                </li>
                                <li><a href="<?php echo $this->url('application') ?>" ><span>Kết quả thi thử TOEIC, IELTS</span></a></li>
                            </ul>
                        </div>
                    </div>
                    <p>
                    <div id="chat" style="width: 100%; height: 200px" class="ui-widget-content ui-corner-all">
                        <div class="panel-header ui-widget-header">
                            Tư vấn trực tuyến
                        </div>
                        <div id="support">

                        </div>
                        <script>
                            $("#support").load("/Sfive/public/application/support");
                        </script>

                    </div>
                    <p>
                    <div id="like-box" style="width: 100%;" class="ui-widget-content ui-corner-all">
                        <div class="panel-header ui-widget-header">
                            Find us on Facebook
                        </div>
                        <div class="fb-like-box" data-href="https://www.facebook.com/sfive.edu.vn" data-width="232" data-show-faces="true" 
                             data-header="false" data-stream="true" data-show-border="true"></div>                    
                    </div>
                </div>
            </div>


        </div>
        <div id="footer" >
            <p style="text-align: center">&copy; <?php echo date('Y') ?> by Sfive English Center. <?php echo $this->translate('All rights reserved.') ?></p>
        </div>
        <div hidden="true" id="copyright">Copyright &copy; 2013 <a href="http://apycom.com/">Apycom jQuery Menus</a></div>
    </body>
    <?php echo $this->inlineScript() ?>
</html>
