

<script>
    $(document).ready(function() {
        console.log("Chúng tôi là ai");
        $("#left-menu").hide();
        $("#entry").width('76.7%');
        layoutAction.run_marquee();
    });
</script>
<div class="ui-widget-header ui-corner-top">
    <?php echo $this->title ?>
</div>
<br>
<br>
<div class="fb-comments" data-href="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>" data-width="750"></div>
<div style="text-align: center" class="ui-widget-header ui-corner-bottom">
</div>
