<script>
    $(document).ready(function() {
        console.log("Chúng tôi là ai");
        $("#left-menu").hide();
        $("#entry").width('75%');
        layoutAction.run_marquee();
    });
</script>
<div class="ui-widget-header ui-corner-top">
    <?php echo $this->title ?>
</div>
<br>
<div>
    <?php
    echo $this->content
    ?>
</div>
<br>
<div class="fb-comments" data-href="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>" data-width="750"></div>