<script>
    $(document).ready(function() {
        console.log("Chúng tôi là ai");
        $("#left-menu").hide();
        $("#entry").width('75%');
        layoutAction.run_marquee();
    });
</script>
<h4><?php echo $this->title ?></h4>
<hr>
<div>
    <?php
    echo $this->content
    ?>
</div>
<div class="fb-comments" data-href="<?php echo 'http://localhost/Sfive/public/articles/detail/' . $this->id ?>" data-width="700"></div>