<?php
    echo $this->headScript()->prependFile($this->basePath() . '/js/article.js');
    $this->headLink()->prependStylesheet($this->basePath() . '/css/article.css');
?>
<div id="MyTableContainer">
    <div class="filtering">
        <table>
            <tr>
                <td>
                    <?php
                    echo $this->formRow($this->form->get('title'));
                    ?>
                </td>
                <td>
                    <?php
                    echo $this->formRow($this->form->get('parent_menu'));
                    ?>
                </td>
                <td>
                    <?php
                    echo $this->formRow($this->form->get('menu'));
                    ?>
                </td>
                <td><input id="articlesearch" onclick="postAction.btnSearchClick();" type="button" class="sfive-button ui-corner-all" value="Tìm kiếm"></td>
            </tr>
        </table>

    </div>
</div>